name: ragc - Rust Build
on: [push]
jobs:
  build-ragc-debug:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Rust Project (Debug)
        run: cargo build

  run-ragc-tests:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    needs:
      build-ragc-debug
    strategy:
      matrix:
        test_name: [mem::timer]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Test ${{matrix.test_name}}
        run: cargo test ${{matrix.test_name}}
